### ISSUE TITLE
Limit profile to one paraglider/harness

### ISSUE THREAD

**Issue by simonseyer** [simonseyer/paraquip#38]
# Why?

Weight and particular wing load calculations only make sense with one wing. The desired wing load can then be set per profile, instead of per profile and wing, simplifying the feature for the user.

For the profile screen, it allows for some simplification because instead of the empty view it can directly offer to set a glider/harness. This removes the buttons to add a glider/harness in the upper right (leaving only reserves and other gear).

The whole concept of profiles is that you go flying with one set of equipment at a time. There it makes no sense to have more than one.

It also allows you to more easily add a "compare profile" feature later.

# Data model

No changes (still a list of equipment). Enforced in UI.

# Tasks 

- [x] Detect profiles with more than one glider/harness and duplicate them after user confirmation (i.e. creating a new profile with the duplicate wing but all other equipment)
- [x] Remove buttons to add glider/harness
- [x] Remove "empty profile view"
- [x] Add plus button in the profile screen for glider/harness when none is present (like a placeholder)
- [x] Let the user choose to select an existing glider/harness or create a new one (when one exists already)
- [x] In the edit profile screen, make glider/harness a single selection
